#!/usr/bin/env bash
# entrypoint.sh — boot the pinned 10.4.57 UniFi Network Application against an
# EXTERNAL MongoDB, configured purely from MONGO_* env so the e2e compose env
# block is identical to the one the linuxserver image consumed (drop-in swap).
#
# It writes /usr/lib/unifi/data/system.properties (the controller reads this on
# startup) to disable the embedded mongod and point both the main and stats
# stores at the external mongo service, then execs the launcher:
#     java -jar /usr/lib/unifi/lib/ace.jar start
#
# Running as root in the container is fine — this is a throwaway test controller.
set -euo pipefail

UNIFI_DIR=/usr/lib/unifi
DATA_DIR="$UNIFI_DIR/data"
PROPS="$DATA_DIR/system.properties"

# Mongo connection (defaults match docker-compose.yml + init-mongo.js). These
# mirror the linuxserver image's contract so the compose `environment:` is
# unchanged across the image swap.
MONGO_HOST="${MONGO_HOST:-mongo}"
MONGO_PORT="${MONGO_PORT:-27017}"
MONGO_DBNAME="${MONGO_DBNAME:-unifi}"
MONGO_USER="${MONGO_USER:-}"
MONGO_PASS="${MONGO_PASS:-}"
MONGO_AUTHSOURCE="${MONGO_AUTHSOURCE:-admin}"
MONGO_TLS="${MONGO_TLS:-false}"

mkdir -p "$DATA_DIR" "$UNIFI_DIR/logs" "$UNIFI_DIR/run"

# Build the optional userinfo (user:pass@) only when credentials are supplied.
AUTH=""
if [ -n "$MONGO_USER" ] && [ -n "$MONGO_PASS" ]; then
  AUTH="${MONGO_USER}:${MONGO_PASS}@"
fi
# authSource is only meaningful with credentials.
QUERY=""
if [ -n "$AUTH" ]; then
  QUERY="?authSource=${MONGO_AUTHSOURCE}"
fi
if [ "$MONGO_TLS" = "true" ]; then
  if [ -n "$QUERY" ]; then QUERY="${QUERY}&tls=true"; else QUERY="?tls=true"; fi
fi

MAIN_URI="mongodb://${AUTH}${MONGO_HOST}:${MONGO_PORT}/${MONGO_DBNAME}${QUERY}"
STAT_URI="mongodb://${AUTH}${MONGO_HOST}:${MONGO_PORT}/${MONGO_DBNAME}_stat${QUERY}"

# Write system.properties fresh on every boot so env changes always win. (A
# restored seed's keystore lives elsewhere in data/; only the mongo wiring is
# regenerated here.)
echo "==> writing $PROPS (external mongo: ${MONGO_HOST}:${MONGO_PORT}/${MONGO_DBNAME})"
cat > "$PROPS" <<EOF
# Generated by entrypoint.sh — external MongoDB wiring (do not hand-edit).
db.mongo.local=false
db.mongo.uri=${MAIN_URI}
statdb.mongo.uri=${STAT_URI}
unifi.db.name=${MONGO_DBNAME}
EOF

echo "==> starting UniFi Network Application (ace.jar start) on :8443"
# JVM flags mirror the .deb's own init script (/usr/lib/unifi/bin/unifi.init) —
# the authoritative launch line. The --add-opens set is REQUIRED on a modern JDK
# (Java 25 here): Spring Data's reflective access to java.time/java.lang/etc. is
# blocked by strong module encapsulation otherwise, and the web context fails to
# initialize ("module java.base does not 'opens java.time'"). We run in the
# foreground (exec, no nohup) so the container's PID 1 is the JVM.
exec java \
  -Dfile.encoding=UTF-8 \
  -Djava.awt.headless=true \
  -Dapple.awt.UIElement=true \
  -Xmx1024M -XX:+UseParallelGC \
  -XX:+ExitOnOutOfMemoryError -XX:+CrashOnOutOfMemoryError \
  -Dunifi.datadir="$DATA_DIR" \
  -Dunifi.logdir="$UNIFI_DIR/logs" \
  -Dunifi.rundir="$UNIFI_DIR/run" \
  --enable-native-access=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED \
  --add-opens java.base/java.time=ALL-UNNAMED \
  --add-opens java.base/sun.security.util=ALL-UNNAMED \
  --add-opens java.base/java.io=ALL-UNNAMED \
  --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED \
  -jar "$UNIFI_DIR/lib/ace.jar" start
